import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;

/**
 * Example 1: seeing erasure at runtime.
 *   1. List<String> and List<Integer> are the same class.
 *   2. What T erases to: Object, or the first bound (found with reflection).
 *   3. A bridge method, and the ClassCastException it throws.
 *   4. Heap pollution: a raw type lets an Integer into a List<String>.
 *   5. instanceof: List<?> works, List<String> doesn't compile.
 *
 * Run: java examples/Example1_Basics.java
 */
public class Example1_Basics {

    static class Node<T> {
        T data;

        void setData(T data) {
            this.data = data;
        }
    }

    // setData(Integer) erases to setData(Integer). The compiler adds a bridge setData(Object).
    static class IntNode extends Node<Integer> {
        @Override
        void setData(Integer data) {
            System.out.println("  IntNode.setData(" + data + ")");
            super.setData(data);
        }
    }

    static class Ranked<T extends Comparable<T>> {
        T best;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})   // this example breaks the rules on purpose
    public static void main(String[] args) throws Exception {
        System.out.println("--- 1. One class at runtime ---");
        List<String> names = new ArrayList<>();
        List<Integer> ids = new ArrayList<>();
        System.out.println("same class? " + (names.getClass() == ids.getClass()) + " (" + names.getClass().getName() + ")");

        System.out.println();
        System.out.println("--- 2. What T becomes ---");
        System.out.println("Node.data is a    " + Node.class.getDeclaredField("data").getType().getSimpleName());
        System.out.println("Ranked.best is a  " + Ranked.class.getDeclaredField("best").getType().getSimpleName());

        System.out.println();
        System.out.println("--- 3. Bridge method ---");
        for (Method m : IntNode.class.getDeclaredMethods()) {
            System.out.println("IntNode has setData(" + m.getParameterTypes()[0].getSimpleName() + ")"
                    + (m.isBridge() ? "  <- bridge, generated by the compiler" : ""));
        }
        Node raw = new IntNode();          // raw type: no compile-time check
        raw.setData(5);                    // goes through the bridge, cast succeeds
        try {
            raw.setData("five");           // the bridge's (Integer) cast fails
        } catch (ClassCastException e) {
            System.out.println("  ClassCastException from the bridge's cast");
        }

        System.out.println();
        System.out.println("--- 4. Heap pollution ---");
        List rawNames = names;
        rawNames.add("Ada");
        rawNames.add(42);                  // an Integer inside a List<String>; nothing fails yet
        System.out.println("names = " + names + " (printing is fine: toString works on anything)");
        try {
            for (String name : names) {    // the hidden (String) cast runs here
                System.out.println("  " + name.toUpperCase());
            }
        } catch (ClassCastException e) {
            System.out.println("  ClassCastException, far from the line that caused it");
        }

        System.out.println();
        System.out.println("--- 5. instanceof ---");
        Object something = ids;
        System.out.println("instanceof List<?>: " + (something instanceof List<?>));
        // something instanceof List<Integer>   // won't compile: the type argument doesn't exist at runtime
    }
}

/* Expected output (the order of the two setData lines can vary between JVMs):
--- 1. One class at runtime ---
same class? true (java.util.ArrayList)

--- 2. What T becomes ---
Node.data is a    Object
Ranked.best is a  Comparable

--- 3. Bridge method ---
IntNode has setData(Integer)
IntNode has setData(Object)  <- bridge, generated by the compiler
  IntNode.setData(5)
  ClassCastException from the bridge's cast

--- 4. Heap pollution ---
names = [Ada, 42] (printing is fine: toString works on anything)
  ADA
  ClassCastException, far from the line that caused it

--- 5. instanceof ---
instanceof List<?>: true
*/
